/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package so1_tarea4;
import clases.Proceso;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author danpu
 */
public class UI extends javax.swing.JFrame {
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jButton5.setText("Inicio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 743, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //BOTON DE INICIO
        int tamMaximo =0;
        int posicion = 0;
        jPanel1.removeAll();
        
        ArrayList<Proceso> procesos = new ArrayList<Proceso>();
        JButton btnProceso1 = new JButton();
        JButton btnProceso2 = new JButton();
        JButton btnProceso3 = new JButton();
        JButton btnProceso4 = new JButton();
        
        btnProceso1.setBounds(0, 0, 30, 30);
        btnProceso2.setBounds(0, 60, 30, 30);
        btnProceso3.setBounds(0, 120, 30, 30);
        btnProceso4.setBounds(0, 180, 30, 30);
        btnProceso1.setEnabled(false);
        btnProceso2.setEnabled(false);
        btnProceso3.setEnabled(false);
        btnProceso4.setEnabled(false);
        
        jPanel1.add(btnProceso1);
        jPanel1.add(btnProceso2);
        jPanel1.add(btnProceso3);
        jPanel1.add(btnProceso4);
        
        
           
        Proceso p1 = new Proceso(0, 0);
        procesos.add(p1);
        Proceso p2 = new Proceso(0, 60);
        procesos.add(p2);
        Proceso p3 = new Proceso(0, 120);
        procesos.add(p3);
        Proceso p4 = new Proceso(0, 180);
        procesos.add(p4);
        btnProceso1.setVisible(true);
        btnProceso2.setVisible(true);
        btnProceso3.setVisible(true);
        btnProceso4.setVisible(true);
        
        Random random = new Random();
                
        while(tamMaximo < 600){
            int tiempoProceso = random.nextInt(6 - 1) + 1;
            System.out.println(tiempoProceso);
            
            int posicionActual = procesos.get(posicion).getPosicionX() + (tiempoProceso * 30);
            procesos.get(posicion).setPosicionX(posicionActual);
            tamMaximo = posicionActual;
            
            
//            switch(posicion){
//                case 0:
//                    //Primero proceos
//                    btnProceso1.setBounds(posicionActual, 0, 30, 30);
//                    Timer t = new Timer(500, new ActionListener(){
//                        @Override
//                        public void actionPerformed(ActionEvent e){
//                            jPanel1.repaint();
//                        }
//                    });
//
//                    t.setRepeats(false);
//                    t.setDelay(500);
//                    t.start();
//                break;
//     
//                case 1:
//                    //Segundo proceso
//                    btnProceso2.setBounds(posicionActual, 60, 30, 30);
//                    
//                    Timer t2 = new Timer(500, new ActionListener(){
//                        @Override
//                        public void actionPerformed(ActionEvent e){
//                            jPanel1.repaint();
//                        }
//                    });
//
//                    t2.setRepeats(false);
//                    t2.setDelay(500);
//                    t2.start();
//                break;
//                
//                case 2:
//                    //Tercer proceso
//                    btnProceso3.setBounds(posicionActual, 120, 30, 30);
//                    
//                    Timer t3 = new Timer(500, new ActionListener(){
//                        @Override
//                        public void actionPerformed(ActionEvent e){
//                            jPanel1.repaint();
//                        }
//                    });
//
//                    t3.setRepeats(false);
//                    t3.setDelay(500);
//                    t3.start();
//                break;
//                
//                case 3:
//                    //Cuarto proceso
//                    btnProceso4.setBounds(posicionActual, 180, 30, 30);
//                    
//                    Timer t4 = new Timer(500, new ActionListener(){
//                        @Override
//                        public void actionPerformed(ActionEvent e){
//                            jPanel1.repaint();
//                        }
//                    });
//
//                    t4.setRepeats(false);
//                    t4.setDelay(500);
//                    t4.start();
//                break;
//                
//                default:
//                break;
//            }
            
            
           

            posicion++;
            if(posicion > 3){
                posicion = 0;
            }
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
